### PR TITLE
add sms notifier

### PR DESCRIPTION
**Pull request by josh-chamberlain**
### Fixes

No issue. I just want to get health monitoring alerts sent to a google phone number.

### Description

Uses [textbelt](https://docs.textbelt.com/) 

- [x] in `check_search_endpoint.py:27–28` I added bits to fire a text no matter what, because I was trying to test. Gotta remove that first
   - ~~incidentally, what's a good way to make this break locally for testing purposes?~~
   - in the README, there are instructions to run `scripts/webhook_logic.py` which has a `__main__` thing for testing. so that's nice
- [x] add `textbelt` credits
- [x] add `TEXTBELT_API_KEY` and `SMS_NUMBER` variables to production environment

### Docs

?

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
@maxachis what's the preferred way to add envars to the automation manager droplet?

**Comment by maxachis** [comment]
@josh-chamberlain In http://automation.pdap.io/job/Health-Monitor/configure, you should see a section called "Build Environment", which includes a section where the WEBHOOK_URL is currently being defined. That would be the spot to add a new environment variable.

**Comment by josh-chamberlain** [comment]
@maxachis thanks, I forgot about that! Updated my README to include it.

~~I think this is a bug~~ it wasn't working with my VPN on

**Comment by maxachis** [comment]
> @maxachis thanks, I forgot about that! Updated my README to include it.
> 
> ~I think this is a bug~ it wasn't working with my VPN on

@josh-chamberlain Speaking of which, we probably want to add an issue to get it the certification needed so that the "Not secure" warning on the page goes away.

**Comment by josh-chamberlain** [comment]
@maxachis not sure what you mean, actually—the built-in node warning? (https://www.jenkins.io/doc/book/security/controller-isolation/)

**Comment by maxachis** [comment]
> @maxachis not sure what you mean, actually—the built-in node warning? (https://www.jenkins.io/doc/book/security/controller-isolation/)

@josh-chamberlain This one!

image

**Comment by josh-chamberlain** [comment]
@maxachis ah, ok! the app platform automatically handles https for us, so we haven't had to do this. https://github.com/Police-Data-Accessibility-Project/meta/issues/221

**Review by maxachis — APPROVED** [review]
Looks good! Approved!

**Pull request merged**
